#
# Cookbook Name:: lb_elb
#
# Copyright RightScale, Inc. All rights reserved.
# All access and use subject to the RightScale Terms of Service available at
# http://www.rightscale.com/terms.php and, if applicable, other agreements
# such as a RightScale Master Subscription Agreement.


module RightScale
  module ELB
    module Helper

      # Creates and returns connection to ELB endpoint
      # 
      # @param [String] account_id AWS Access ID key
      # @param [String] account_secret AWS Secret key
      # 
      # @return [ELB] ELB interface object

      def get_elb_object(account_id, account_secret)

        require "right_cloud_api"
        require "cloud/aws/elb/manager"

        # URL endpoint is based on AWS region which is generated by removing the
        # trailing letter from the availability zone.
        # e.g. us-west-2a -> us-west-2
        region = node[:ec2][:placement][:availability_zone].gsub(/[a-z]+$/, '')

        url_endpoint = "https://elasticloadbalancing.#{region}.amazonaws.com"

        # Create and return ELB interface object.
        RightScale::CloudApi::AWS::ELB::Manager::new(
          account_id,
          account_secret,
          url_endpoint
        )

      end

    end
  end
end
